### PR TITLE
Enable `$` symbol as inline math delimiter

### PR DESCRIPTION
**Pull request by robertodr**
Both `$` and `\\(`, `\\)` can be used as inline math delimiter. This removes the need to use backticks to start an inline math environment, which causes inline symbols to have a grey shading. **WARNING** This might possibly break slide decks with inline math using backticks.

### CODE REVIEW

**Comment by bast** [comment]
This PR now conflicts - sorry if this was induced by me. This will not affect "$" inside code blocks, right (inline or separate)?

**Comment by robertodr** [comment]
@bast I haven't tried yet. We can shelf this PR until later. I think I'll have some more MathJax "tricks" by the end of this trip :wink: and it's then better to have them in one PR

**Comment by bast** [comment]
I will also test it on my side ASAP.

**Comment by bast** [comment]
Thanks! I have just incorporated this. It seems to behave fine.

**Pull request closed without merging**
