### PR TITLE
Add support for MathJax and an example slide

### PR DESCRIPTION
**Pull request by robertodr**

### CODE REVIEW

**Comment by bast** [comment]
Thanks a lot! Brilliant! Will integrate it in a day or two.

**Comment by robertodr** [comment]
In hindsight, it might not be that great. Unless you offer a static copy of MathJax in `static/js`. Downside is that this will push the size of the repository up...
A possibly better solution would be for `cicero.py` to look for user-provided `static` and `templates` directories and use the standard ones as fallback. The user can fudge his/her style as much as he/she wants, while the basic service remains lightweight. It doesn't sound too complicated to implement, but I wouldn't know how to do it off the top of my head...

**Comment by bast** [comment]
I agree that there should be an option to have them locally. Will see how to best solve it.

**Comment by bast** [comment]
Thank you!

**Pull request merged**
